apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.statefulset.nameSpace }}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.labels.app }}
    spec:
      containers:
      - name: {{ .Values.statefulset.specContainerName }}
        image: {{ .Values.statefulset.image }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.statefulset.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.statefulset.resources.requests.cpu }}
        ports:
        - containerPort: {{ .Values.statefulset.ports.containerPort }}
          name: rest
          protocol: TCP
        - containerPort: {{ .Values.statefulset.ports.containerInterPort }}
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: cluster.name
          value: k8s-logs
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "es-cluster-0.elasticsearch"
        - name: cluster.initial_master_nodes
          value: "es-cluster-0"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: network.host
          value: "_site_"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ .Values.statefulset.metadata.labels.app }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.statefulset.storageClass }}
      resources:
        requests:
          storage: {{ .Values.statefulset.specResourceRequestStorage }}