apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.graylog.namespace }}
  labels:
    app: graylog
spec:
  replicas: {{ .Values.graylog.replicaCount }}
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.graylog.image.repository }}
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: RUTIHBihcCLZv6mOj2aF8QxM272enk88iAiRavnylCmSNZZif2bUZT9xb5xWbI6w
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 9592fb24347cdfff42df6f643b9d3d98414596d6f3af6a33b3be026ec040bc52 
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elasticsearch.graylog-demo.svc.cluster.local:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:27017/graylog
        - name: TZ
          value: Asia/Kolkata
        - name: GRAYLOG_ROOT_TIMEZONE
          value: Asia/Kolkata
        - name: GRAYLOG_TIMEZONE
          value: Asia/Kolkata
        ports:
        - containerPort: {{ .Values.graylog.deploy.containerPort1 }}
        - containerPort: {{ .Values.graylog.deploy.containerPort2 }}