apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.serviceAccount.mname }}
  namespace: {{ .Values.mongodb.namespace }}
immutable: false  
data:
  username: mongoadmin  
  mongodb.conf: |  
    storage:
      dbPath: /data/db  
    replication:
      replSetName: "repl-set"  # important!!