apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{ .Values.daemonset.nameSpace }}
  labels:
    app: {{ .Values.daemonset.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.daemonset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.daemonset.labels.app }}
    spec:
      serviceAccount: {{ .Values.daemonset.serviceAccountName }}
      serviceAccountName: {{ .Values.daemonset.serviceAccountName }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Values.daemonset.specContainerName }}
        image: {{ .Values.daemonset.image }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.elk.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: /var/log/containers/fluent*
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/ 
        resources:
          limits:
            memory: {{ .Values.daemonset.limitMemory }}
          requests:
            cpu: {{ .Values.daemonset.requestCPU }}
            memory: {{ .Values.daemonset.requestMemory }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: {{ .Values.daemonset.terminationPeriod }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers