apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.elastic.storageClass }}
  namespace: {{ .Values.elastic.storageNameSpace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fluentd
    meta.helm.sh/release-namespace: default
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none