apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistentVolume.path }}
