{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.nameSpace }}
  labels:
    app: {{ .Values.serviceAccount.labels.app }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fluentd-release
    meta.helm.sh/release-namespace: kube-log
{{- end }}
