apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.statefulset.nameSpace }}
spec:
  serviceName: {{ .Values.statefulset.spec.serviceName }}
  replicas: {{ .Values.statefulset.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.spec.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.spec.serviceName }}
    spec:
      containers:
      - name: {{ .Values.statefulset.spec.serviceName }}
        image: {{ .Values.statefulset.spec.template.image }}
        ports:
        - containerPort: {{ .Values.statefulset.spec.template.ports.containerPort }}
          name: restapi
          protocol: TCP
        - containerPort: {{ .Values.statefulset.spec.template.ports.containerPortn2n }}
          name: node2node
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.statefulset.spec.template.volumeMounts.name }}
          mountPath: {{ .Values.statefulset.spec.template.volumeMounts.mountPath }}
        env:
          - name: cluster.name
            value: demo-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cls-0.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cls-0"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:    ## 3 busybox images to handle neccesary jobs before ES cluster goes up.
      - name: configure-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: {{ .Values.statefulset.spec.template.volumeMounts.name }}
          mountPath: {{ .Values.statefulset.spec.template.volumeMounts.mountPath }}
      - name: configure-vm-max-map-count
        image: {{ .Values.statefulset.spec.template.initContainers.image }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: configure-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true   
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.statefulset.spec.volumeClaimTemplates.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.statefulset.spec.volumeClaimTemplates.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.statefulset.spec.volumeClaimTemplates.spec.resources.storage }}