kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.elasticservice.serviceName }}
  namespace: {{ .Values.elasticservice.nameSpace }}
  labels:
    app: {{ .Values.elasticservice.serviceName }}
spec:
  selector:
    app: {{ .Values.elasticservice.serviceName }}
  clusterIP: None
  ports:
    - port: {{ .Values.elasticservice.port }}
      name: rest
    - port: 9300
      name: inter-node
